version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - apt-get update && apt-get install -y python3-venv
      - python -m venv test_venv
      - . test_venv/bin/activate
      - pip install --upgrade pip
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  pre_build:
    commands:
      - mkdir test-reports    
  build:
    commands:
      - echo "Zipping deployment package..."
      - ls -la
      - cd test_venv && cd bin && cd python
      - zip -r9 ../../../deployment_package.zip .
      - cd ../../..
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name testLambda --zip-file fileb://deployment_package.zip
      - echo "DONE!!"
      - echo "running tests"
      - export PYTHONPATH=.
      - which python
      - python -m pytest --html=test-reports/report.html --self-contained-html -s -v --cov=tests --cov-report=html:test-reports/coverage --junitxml=test-reports/junit.xml --log-file=test-reports/logs.txt tests
      - echo Build completed on `date`  
reports:
  coverage:
    files:
      - "coverage/*"
    base-directory: 'test-reports'
    discard-paths: yes
  report:
    files:
      - 'junit.xml'
      - 'report.html'
      - 'assets/*'
    base-directory: 'test-reports'
    discard-paths: yes
    file-format: JunitXml    